apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: c-demo
  namespace: argocd  # Make sure this namespace matches the ArgoCD namespace
spec:
  project: default

  source:
    repoURL: https://github.com/rishi146196/c_demo.git
    targetRevision: HEAD
    path: k8s  # Path where k8s manifests are located in your repo

  destination:
    server: https://kubernetes.default.svc
    namespace: default  # Ensure this points to the target namespace for deployment

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
