apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: c-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rishi146196/c_demo.git'
    targetRevision: HEAD
    path: k8s  # The folder where deployment.yaml and service.yaml are
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
