apiVersion: apps/v1
kind: Deployment
metadata:
  name: c_demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: c_demo
  template:
    metadata:
      labels:
        app: c_demo
    spec:
      containers:
      - name: c_demo
        image: rushikesh196/c_demo
        ports:
        - containerPort: 5000
