apiVersion: apps/v1
kind: Deployment
metadata:
  name: c-demo
  namespace: default  # Added namespace here
spec:
  replicas: 2
  selector:
    matchLabels:
      app: c-demo
  template:
    metadata:
      labels:
        app: c-demo
    spec:
      containers:
      - name: c-demo
        image: rushikesh196/c_demo
        ports:
        - containerPort: 5000
