apiVersion: v1
kind: Service
metadata:
  name: property-verifier-service
spec:
  selector:
    app: property-verifier
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
