apiVersion: v1
kind: Service
metadata:
  name: c-demo
  namespace: default  # Added namespace here
spec:
  selector:
    app: c-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
