apiVersion: v1
kind: Service
metadata:
  name: c-demo
  namespace: default  # Ensure this matches your namespace
spec:
  selector:
    app: c-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer  # Consider changing to NodePort or ClusterIP depending on your needs
