pipeline {
    agent any

    environment {
        IMAGE_NAME = "C_demo"
        DOCKER_REGISTRY = "rushikesh196/C_demo"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/rishi146196/C_demo.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh '''
                    echo $PASSWORD | docker login -u $USERNAME --password-stdin
                    docker tag $IMAGE_NAME $DOCKER_REGISTRY
                    docker push $DOCKER_REGISTRY
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
                sh 'kubectl apply -f k8s/service.yaml'
            }
        }
    }
}
